# Generated by Django 5.0.1 on 2024-01-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=60)),
                ('lb_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
