# Generated by Django 5.0.1 on 2024-01-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
