# Generated by Django 5.0.1 on 2024-01-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
